version: "3.8"
services:
    mongodb:
        image: mongo:7.0
        ports:
            - "27017:27017"
        volumes:
            - mongodb-data:/data/db
    rabbitmq:
        image: rabbitmq:3.12-management
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq/
volumes:
    mongodb-data:
    rabbitmq-data:
